"""Add city state postal_code country image_url to properties

Revision ID: 74f20387d61b
Revises: 2ee80e442254
Create Date: 2026-01-03 20:45:34.809013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f20387d61b'
down_revision: Union[str, None] = '2ee80e442254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed leads and viewings table creation - already exist
    op.add_column('properties', sa.Column('city', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('state', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('country', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('image_url', sa.String(), nullable=True))
    # Note: Removed alter_column for users.role - not compatible with SQLite
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'image_url')
    op.drop_column('properties', 'country')
    op.drop_column('properties', 'postal_code')
    op.drop_column('properties', 'state')
    op.drop_column('properties', 'city')
    # ### end Alembic commands ###
